### ISSUE TITLE
.ask in the AHK Discord can be counterintuitive

### ISSUE THREAD

**Issue by IsaacElenbaas** [Run1e/AceBot#38]
When someone responds with `.ask` in `#general`, either with a ping or at a slow time of day, the asker may see the message much later. The suggested channels may have been claimed, and the newcomer just doing what they were told accidentally asks in the wrong place a second time.

Ace should store a queue of tuples containing old message IDs, suggested channel 1, and suggested channel 2. When a channel is claimed, Ace should edit the next queue item to instead point to `#how-to-get-help` until neither of the next queue item's suggested channels are the just claimed channel.

**Comment by Run1e** [comment]
Obsolete because of moving to help forums.
