### ISSUE TITLE
Mutes don't Always Reset

### ISSUE THREAD

**Issue by onerandomusername** [Run1e/AceBot#42]
In some cases, unmuting a user does not always clear the record in the database that a user was temporarily muted.

I've narrowed it down to be a cause of having a is_bot check when updating the database. 

There's two possible solutions. One solution is to prevent muting bots, which I am personally against. The other solution is to remove the check for if the member is a bot when unmuting them.

![image](https://user-images.githubusercontent.com/71233171/116901998-9980c100-ac08-11eb-8e34-d467e33356e6.png)
https://github.com/Run1e/AceBot/blob/5e2ac950d780d22d25406a28e352c68b16c43246/cogs/mod.py#L357
https://github.com/Run1e/AceBot/blob/5e2ac950d780d22d25406a28e352c68b16c43246/cogs/mod.py#L609-L611

**Comment by onerandomusername** [comment]
After some more testing, its also possible for mutes to fail if a user has the muted role manually removed during a tempmute and the listener does not run. For example, Ace is down and a user is manually unmuted, or the cog failed to load, or other things.

**Comment by snaphat** [comment]
You shouldn't remove the ability to mute bots. The second option is how it should work in my opinion even if it requires a special check for bots
