### ISSUE TITLE
[Request] Make help channels auto-close when the initial message gets deleted

### ISSUE THREAD

**Issue by SimplyMika** [Run1e/AceBot#45]
Title says it all. It happens from time to time that somebody opens a help channel (usually they trigger the ‘anti-cheat’ message) and then just decide to delete their message (or maybe Staff does). In this case the channel just lingers around for 30 minutes.
If it's not too big of a deal, I would like to see it close automatically in this case. I guess there would have to be a check that there are no other non-bot messages in the channel. Not sure.
That's all!

**Comment by onerandomusername** [comment]
I'm thinking a good implementation for this would be if the first message is deleted and there is not a second message then wait 2 minutes before closing.

I don't see a need to detect if both the first and second messages are deleted, however. That happens very rarely from what I can tell.

**Comment by SimplyMika** [comment]
My thought was that Ace already keeps track of channels that are ‘new’ (they get the :exclamation: emoji added). So it should be pretty simple to only apply this rule to help channels which are still considered ‘new’.

But yeah, simply reducing the time it takes to close would probably a good idea instead of outright closing it immediately, in case the author just wanted to rephrase or correct what they said and didn't choose to use the edit function. Or maybe they wanted to attach an image (can't be done through editing).

**Comment by Run1e** [comment]
Obsolete because of moving to help forums.
