### ISSUE TITLE
Double error messages

### ISSUE THREAD

**Issue by itayVolk** [Run1e/AceBot#84]
Ror some reason error messages show both as ephemeral and as regular messages
![image](https://github.com/user-attachments/assets/f70151a2-2dec-4137-90c7-bf9ca0023685)

**Comment by onerandomusername** [comment]
Can reproduce. This is probably a bug in the error handler.

**Comment by Run1e** [comment]
fixed in fd4be3c1520dedbdc9d9e2700c13a4fbf43a3a55
